spring:
  application:
    name: Authenticate

server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      default-zone: http://localhost:8761/eureka

#Actuator and circuit breaker
management:
  endpoints:
    routes:
      enabled: true
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      payment-service:
#        registerHealthIndicator: true
#        event-consumer-buffer-size: 100
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#
#  timelimiter:
#    instances:
#      payment-service:
#        timeout-duration: 3s
